### ISSUE TITLE
FRE: Systemd template k0s.service.j2 alignment

### ISSUE THREAD

**Issue by usrbinkat** [movd/k0s-ansible#2]
Recommended: resolve deltas between k0s systemd service file and k0s systemd service file for consistency & experience integrity.

Compare:
A) movd/k0s-ansible systemd template: [roles/k0s/initial_controller/templates/k0s.service.j2](https://github.com/movd/k0s-ansible/blob/main/roles/k0s/initial_controller/templates/k0s.service.j2)
B) k0sproject/k0s systemd example: [init/k0s.service](https://github.com/k0sproject/k0s/blob/main/init/k0s.service)

**Comment by movd** [comment]
Thanks so much for pointing this out! 

I should have looked through the repository to use implementation you contributed. Instead, I put the file together myself and later aligned it with the way `k0s install` creates the unit file: https://github.com/k0sproject/k0s/blob/main/pkg/install/service.go

Maybe we should wait until a decision has been in the k0s repo which systemd template to use. I created an issue https://github.com/k0sproject/k0s/issues/605

**Comment by usrbinkat** [comment]
Perfect, I agree and was hoping to align the file with the results of the `k0s install` command results once that simmers  down.

**Comment by usrbinkat** [comment]
Static file example merged into [k0sproject/k0s/pkg/install/service.go](https://github.com/k0sproject/k0s/blob/main/pkg/install/service.go#L79-L108) in PR https://github.com/k0sproject/k0s/pull/607 

Closing issue following closure of https://github.com/k0sproject/k0s/issues/605 

Will open new issue to track adoption of `k0s install` sub cmd in k0s-ansible
